services:
  money-talk:
    image: chartester/money-talk
    build:
      args:
        - MONGO_URL=${MONGO_URL}
        - MONGO_DB_NAME=${MONGO_DB_NAME}
        - JWT_SECRET=${JWT_SECRET}
        - APP_USERNAME=${APP_USERNAME}
        - APP_PASSWORD=${APP_PASSWORD}
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - APP_USERNAME=${APP_USERNAME}
      - APP_PASSWORD=${APP_PASSWORD}
